global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aetheriq'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Remote write configuration (optional)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     basic_auth:
#       username: admin
#       password: admin

# Remote read configuration (optional)
# remote_read:
#   - url: "http://remote-storage:9201/read"
#     basic_auth:
#       username: admin
#       password: admin 